name: Validate with hassfest

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 0 * * *'

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out repository
        uses: "actions/checkout@v3.2.0"
        with:
          fetch-depth: 2

      - uses: home-assistant/actions/hassfest@master
