name: Push

on: [push, pull_request]

jobs:
  check:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install requirements
      run: |
        pip install -r requirements-test.txt
    - name: Check with isort
      run: |
        isort custom_components/zadnego_ale tests --check-only
    - name: Check with Black Code Formatter
      run: |
        black custom_components/zadnego_ale tests --check
    - name: Lint with flake8
      run: |
        flake8 custom_components/zadnego_ale tests
    - name: Lint with pylint
      run: |
        pylint custom_components/zadnego_ale
    - name: Test with mypy
      run: |
        mypy custom_components/zadnego_ale
    - name: Test with pytest
      run: |
        pytest tests --cov=custom_components/zadnego_ale --cov-report term-missing --disable-pytest-warnings
