---
name: Push

"on": [push, pull_request]

jobs:
  check:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: |
          pip install -r requirements-test.txt
      - name: Check with isort
        run: |
          isort custom_components/zadnego_ale tests --check-only
      - name: Check with Black Code Formatter
        run: |
          black custom_components/zadnego_ale tests --check
      - name: Lint with flake8
        run: |
          flake8 custom_components/zadnego_ale tests
      - name: Lint with pylint
        run: |
          pylint custom_components/zadnego_ale
      - name: Test with mypy
        run: |
          mypy custom_components/zadnego_ale
      - name: Test with pytest
        run: |
          pytest tests
